FROM ksauzz/centos-base

MAINTAINER Kazuhiro Suzuki <ksauzzmsg@gmail.com>

RUN yum install -y gcc gcc-c++ glibc-devel make git
RUN yum install -y ncurses-devel openssl-devel autoconf
RUN yum install -y rpm-build tar which


