FROM ksauzz/base

MAINTAINER Kazuhiro Suzuki <ksauzzmsg@gmail.com>

RUN apt-get install --no-install-recommends -y build-essential libncurses5-dev openssl libssl-dev fop xsltproc unixodbc-dev
RUN apt-get install --no-install-recommends -y curl lsb-release git wget openssh-server
RUN apt-get clean
